version: "3.7"
networks:
  default:
    name: webhookinbox

services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    links:
      - "pushpin"
      - "redis"
    volumes:
      - ./env.example:/app/.env
  pushpin:
    container_name: pushpin
    build:
      context: ./
      dockerfile: Dockerfile.pushpin
    restart: unless-stopped
    ports:
      - "7999:7999"
    volumes:
      - ./routes:/etc/pushpin/routes

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
