version: "3.7"
networks:
  default:
    name: webhookinbox

services:
  app:
    container_name: app
    build:
      context: ./
    restart: unless-stopped
    ports:
      - "7999:7999"
    links:
      - "redis"

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
