apiVersion: v1
kind: ConfigMap
metadata:
  name: routes-config
data:
  routes: |-
    * localhost:8000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
data:
  .env: |-
    GRIP_URL=http://localhost:5561
    WHINBOX_API_BASE=http://ingress.kubernetes/api
    REDIS_HOST=redis.redis.svc.cluster.local
    REDIS_PORT=6379
    REDIS_DB=0