apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhookinbox
spec:
  selector:
    matchLabels:
      app: webhookinbox
  template:
    metadata:
      labels:
        app: webhookinbox
    spec:
      volumes:
        - name: routes-config
          configMap:
            name: routes-config
        - name: env-config
          configMap:
            name: env-config
      containers:
      - name: app
        image: zimbres/webhookinbox
        resources:
          requests:
            memory: "100Mi"
            cpu: "0.1"
          limits:
            memory: "500Mi"
            cpu: "0.5"
        env:
          - name: TZ
            value: America/Sao_Paulo
        volumeMounts:
          - name: env-config
            mountPath: "/app/.env"
            subPath: .env
      - name: pushpin
        image: zimbres/pushpin
        resources:
          requests:
            memory: "100Mi"
            cpu: "0.1"
          limits:
            memory: "500Mi"
            cpu: "0.5"
        ports:
        - containerPort: 7999
        env:
          - name: TZ
            value: America/Sao_Paulo
        volumeMounts:
          - name: routes-config
            mountPath: "/etc/pushpin/routes"
            subPath: routes
