#!/usr/bin/env python
import sys
import json
from urllib import urlencode
import urllib2

if len(sys.argv) < 2:
	print 'usage: webhookinbox new (service base url)'
	print '       webhookinbox delete [inbox url]'
	print ''
	sys.exit(1)

command = sys.argv[1]

if command == 'new':
	if len(sys.argv) >= 3:
		service_base_url = sys.argv[2]
	else:
		service_base_url = 'http://api.webhookinbox.com'

	params = {'ttl': 3600}
	try:
		resp = urllib2.urlopen(urllib2.Request(service_base_url + '/create/', urlencode(params), {}))
	except Exception as e:
		print 'Failed to create inbox: %s' % e.message

	resp = json.loads(resp.read())
	print resp['base_url'] 
elif command == 'delete':
	if len(sys.argv) < 3:
		print 'delete command requires arguments'
		sys.exit(1)

	try:
		req = urllib2.Request(sys.argv[2], None, {})
		req.get_method = lambda: 'DELETE'
		resp = urllib2.urlopen(req)
	except Exception as e:
		print 'Failed to delete inbox: %s' % e.message
else:
	print 'unknown command: %s' % command
